### ISSUE TITLE
Rename the command name to "gistly"

### ISSUE THREAD

**Issue by AsaiToshiya** [dcai/gistly#2]
"gistly" is a great name, but the command name is "gist".

What is the intention of this name?

I think "gistly" is more appropriate to avoid misuse, but what do you think?

Thank you!

**Comment by dcai** [comment]
I agree @AsaiToshiya, I will rename it later

**Comment by AsaiToshiya** [comment]
Thank you for agreeing to my suggestion.

**Comment by dcai** [comment]
@AsaiToshiya  it's renamed now

**Comment by AsaiToshiya** [comment]
@dcai Awesome!
